/**
 * Design-system rules generator.
 *
 * Mirrors the official Figma MCP's `create_design_system_rules`: it turns the
 * design's ACTUAL extracted tokens (colors, type ramp, spacing, radii, shadows)
 * into a rules file an AI agent reads before generating code — so output uses
 * the real design system instead of inventing ad-hoc values.
 *
 * Input is the token set produced by tokens.js `extractTokens`.
 */

const px = (v) => (v >= 9999 ? '9999px' : `${v}px`);

function listColors(colors = []) {
  if (!colors.length) return '_None detected._';
  return colors
    .slice(0, 40)
    .map((c) => `- \`${c.name}\` → \`${c.value}\``)
    .join('\n');
}

function listRamp(items = [], unit = 'px') {
  if (!items.length) return '_None detected._';
  return items
    .map((i) => `- \`${i.name}\` → \`${typeof i.value === 'number' ? i.value + unit : i.value}\``)
    .join('\n');
}

function listFonts(families = []) {
  if (!families.length) return '_None detected._';
  return families.map((f) => `- \`${f.value}\``).join('\n');
}

function listShadows(shadows = []) {
  if (!shadows.length) return '_None detected._';
  return shadows.map((s) => `- \`${s.name}\` → \`${s.value}\``).join('\n');
}

const FRAMEWORK_GUIDANCE = {
  'react-tailwind':
    '- Use Tailwind utility classes. Map the tokens below to your `tailwind.config` `theme.extend` (run `get_design_tokens --format=tailwind4` to generate it).\n' +
    '- Vertical auto-layout → `flex flex-col`; horizontal → `flex flex-row`. Use `gap-*` for item spacing.',
  vue:
    '- Use `<script setup>` SFCs and scoped styles. Reference the CSS variables below (run `get_design_tokens --format=css`).',
  svelte: '- Use Svelte components with a scoped `<style>` block referencing the CSS variables below.',
  angular: '- Use standalone components with inline styles referencing the CSS variables below.',
  html: '- Use semantic HTML + a `:root` CSS variable block (run `get_design_tokens --format=css`).',
  flutter: '- Map colors to `Color(0xFF…)`, the type ramp to `TextStyle`, and spacing to `EdgeInsets`/`SizedBox`.',
  swiftui: '- Map colors to `Color(red:green:blue:)`, the type ramp to `.font(.system(size:))`, spacing to `.padding()`/`Spacer()`.'
};

/**
 * Build a design-system rules markdown document from extracted tokens.
 *
 * @param {object} tokens result of extractTokens()
 * @param {object} [opts]
 * @param {string} [opts.framework='react-tailwind']
 * @param {string} [opts.projectName='This project']
 */
export function generateDesignSystemRules(tokens, opts = {}) {
  const framework = opts.framework || 'react-tailwind';
  const projectName = opts.projectName || 'This project';
  const t = tokens || {};
  const guidance = FRAMEWORK_GUIDANCE[framework] || FRAMEWORK_GUIDANCE['react-tailwind'];
  const sourceNote =
    t.source === 'variables'
      ? 'Derived from the file’s published Figma Variables.'
      : 'Inferred by scanning the design (no published variables found).';

  return `# Design System Rules

> Auto-generated by OpenFigma MCP from the Figma design. ${sourceNote}
> ${projectName} must use these tokens as the single source of truth. Do **not**
> invent ad-hoc colors, font sizes, spacing, or radii — use the names below.

## Framework
Target: **${framework}**
${guidance}

## Colors
Use these named colors. Match the closest token rather than introducing a new hex.

${listColors(t.colors)}

## Typography

### Font families
${listFonts(t.fontFamilies)}

### Font sizes
${listRamp(t.fontSizes, 'px')}

### Font weights
${listRamp(t.fontWeights, '')}

### Line heights
${listRamp(t.lineHeights, 'px')}

## Spacing
Use these spacing steps for padding, margin, and gaps.

${listRamp(t.spacing, 'px')}

## Border radius
${listRamp((t.radius || []).map((r) => ({ name: r.name, value: r.value })), 'px')}

## Shadows / elevation
${listShadows(t.shadows)}

## Layout rules
- Map Figma auto-layout **vertical** stacks to a column flex container; **horizontal** to a row.
- Use the design's \`itemSpacing\` as the gap; use the frame padding values verbatim.
- Preserve the node hierarchy and ordering from \`get_metadata\` / \`get_figma_data\`.
- Respect constraints: a child set to stretch horizontally should be full-width.

## Assets
- Download raster/vector assets with \`download_assets\` (or \`get_image_fills\` for uploaded images) into \`/figma-export/\` and reference them by that path.
- Prefer inline SVG from \`extract_vectors\` for icons (themeable via \`currentColor\`).

## Accessibility
- Run \`audit_accessibility\` and fix any contrast failures before shipping.
- Maintain the contrast and tap-target sizes the audit reports.
`;
}
